// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("BigAssTextFiles")>]
[<assembly: AssemblyProductAttribute("BigAssTextFiles")>]
[<assembly: AssemblyDescriptionAttribute("search and sample very large text files")>]
[<assembly: AssemblyVersionAttribute("0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "BigAssTextFiles"
    let [<Literal>] AssemblyProduct = "BigAssTextFiles"
    let [<Literal>] AssemblyDescription = "search and sample very large text files"
    let [<Literal>] AssemblyVersion = "0.1"
    let [<Literal>] AssemblyFileVersion = "0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
